### ISSUE TITLE
.NET 6.0 Update

### ISSUE THREAD

**Issue by welly87** [AdaptiveConsulting/Aeron.NET#118]
Hi @JPWatson 

I try to upgrade to `netstandard` and `netcore3.1` to `net6.0` then i run IpcThroughput

here's the result before upgrading

```sh
Duration 1,000ms - 10,062,930 messages - 322,013,760 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,063,976 messages - 322,047,232 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,065,513 messages - 322,096,416 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,057,301 messages - 321,833,632 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,057,799 messages - 321,849,568 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,060,503 messages - 321,936,096 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,062,570 messages - 322,002,240 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,062,352 messages - 321,995,264 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,059,734 messages - 321,911,488 bytes, GC0 0, GC1 0, GC2 0
```

then after upgrading

```sh
Duration 1,000ms - 9,474,969 messages - 303,199,008 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,474,044 messages - 303,169,408 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,471,702 messages - 303,094,464 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,473,014 messages - 303,136,448 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,475,162 messages - 303,205,184 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,474,305 messages - 303,177,760 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,432,768 messages - 301,848,576 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,465,044 messages - 302,881,408 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,467,925 messages - 302,973,600 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 9,468,866 messages - 303,003,712 bytes, GC0 0, GC1 0, GC2 0
```

The environment i use is `Amazon Linux 2022` on Graviton3 (ARM Neoverse V1) AWS c7g. 

Looks weird. Will try to find out. It's also resulting the same stuff even after i try to disable/enable PGO and Tiered Compilation.

1. Is that why you don't upgrade the dotnet and still use it for old .NET version? 
2. seems currently it's windows only? I might send pull request for Linux if that's interest you

Cheers

**Comment by welly87** [comment]
btw, after trying brute force for JIT runtime parameters finally arrived with this env var

```sh
export DOTNET_TieredPGO=1
export DOTNET_TieredCompilation=1
```

now i got better result. :)

```sh
Duration 1,000ms - 10,157,651 messages - 325,044,832 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,157,291 messages - 325,033,312 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,161,630 messages - 325,172,160 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,163,553 messages - 325,233,696 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,162,595 messages - 325,203,040 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,157,869 messages - 325,051,808 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,159,737 messages - 325,111,584 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,161,208 messages - 325,158,656 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,157,887 messages - 325,052,384 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,156,317 messages - 325,002,144 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,156,620 messages - 325,011,840 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,158,093 messages - 325,058,976 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,158,585 messages - 325,074,720 bytes, GC0 0, GC1 0, GC2 0
Duration 1,000ms - 10,157,249 messages - 325,031,968 bytes, GC0 0, GC1 0, GC2 0
```

**Comment by JPWatson** [comment]
Interesting results. Thanks, @welly87.

> Is that why you don't upgrade the dotnet and still use it for old .NET version?

Targetting the lowest common denominator from a library perspective so I hadn't got around to testing the latest and greatest .net version.

> seems currently it's windows only? I might send pull request for Linux if that's interest you

We've got [builds](https://github.com/AdaptiveConsulting/Aeron.NET/blob/master/.github/workflows/dotnet.yml#L16) running on both windows and linux. What are you seeing that's windows only?

**Comment by welly87** [comment]
Something about retriving system information or diagnostics. Also NUnit runners. 

I will share with you the details later. On my way home now.

**Comment by welly87** [comment]
basically first time i clone the repo and run `IpcThrougput` it show error

```csharp
❯ Samples/Adaptive.Aeron.Samples.IpcThroughput/bin/Release/net6.0/Adaptive.Aeron.Samples.IpcThroughput
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at HardwareInformation.MachineInformationGatherer.GatherInformation(Boolean skipClockspeedTest, Boolean invalidateCache, ILogger`1 logger)
   at Adaptive.Aeron.Samples.Common.ComputerSpecifications..ctor() in /home/ec2-user/Aeron.NET/src/Samples/Adaptive.Aeron.Samples.Common/ComputerSpecifications.cs:line 51
   at Adaptive.Aeron.Samples.Common.ComputerSpecifications.Dump() in /home/ec2-user/Aeron.NET/src/Samples/Adaptive.Aeron.Samples.Common/ComputerSpecifications.cs:line 93
   at Adaptive.Aeron.Samples.IpcThroughput.IpcThroughput.Main() in /home/ec2-user/Aeron.NET/src/Samples/Adaptive.Aeron.Samples.IpcThroughput/IpcThroughput.cs:line 37
```

i try to restore the the nuget package but seems it can't resolve the `HardwareInformation` dependencies. It builds fine but have runtime errors. So i just commented this line

```cs
// ComputerSpecifications.Dump();
```

just to make the runtime happy....

**Comment by welly87** [comment]
another stuff that seems funny is when running on dotnet3.1 on AmazonLinux2022/Graviton3 seems that nunit runner throw SSL errors when `dotnet test`

but after i upgrade to .NET 6.0 it's magically disappeared. The good stuff is .NET getting better and better each release. 

```csharp
Passed!  - Failed:     0, Passed:   225, Skipped:     0, Total:   225, Duration: 354 ms - /home/ec2-user/Aeron.NET/src/Adaptive.Agrona.Tests/bin/Debug/net6.0/Adaptive.Agrona.Tests.dll (net6.0)
  Adaptive.Aeron.Tests -> /home/ec2-user/Aeron.NET/src/Adaptive.Aeron.Tests/bin/Debug/net6.0/Adaptive.Aeron.Tests.dll
Test run for /home/ec2-user/Aeron.NET/src/Adaptive.Aeron.Tests/bin/Debug/net6.0/Adaptive.Aeron.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.3.0 (arm64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped ShouldAllowConcludeOfClonedContext [< 1 ms]
  Skipped ShouldNotAllowConcludeMoreThanOnce [< 1 ms]
  Skipped BasicMessageTest [4 ms]
```

**Comment by welly87** [comment]
I push my experiment here if you want to take a look

https://github.com/welly87/Aeron.NET/

and put some notes here

https://github.com/welly87/Aeron.NET/blob/master/graviton.md

**Comment by JPWatson** [comment]
Thanks, @welly87. I will take a look asap.
